config/routes.rb
Rails.application.routes.draw do
  resources :customers do
    resources :order_items, except: [ :index ]
    resources :payment_details, except: [ :update, :edit ]
  end

  devise_for :users

  resources :menu_items

  resources :customer_tables

  resources :users, only: [ :index ]

  root "menu_items#index"
end

app/controllers/customer_tables_controller.rb
class CustomerTablesController < ApplicationController
  before_action :authenticate_user!, except: [ :index ]
  before_action :set_customer_table, only: %i[ show edit update destroy ]

  # GET /customer_tables or /customer_tables.json
  def index
    @customer_tables = CustomerTable.paginate(page: params[:page], per_page: 4)
  end

  def show
  end

  # GET /customer_tables/new
  def new
    @customer_table = CustomerTable.new
  end

  # POST /customer_tables or /customer_tables.json
  def create
    @customer_table = CustomerTable.new(customer_table_params)

    if @customer_table.save
      flash.now[:notice] = "Customer table was successfully created."
      redirect_to customer_tables_path
    else
      render :new, status: :unprocessable_entity
    end
  end


  # GET /customer_tables/1/edit
  def edit
  end

  # PATCH/PUT /customer_tables/1 or /customer_tables/1.json
  def update
    if @customer_table.update(customer_table_params)
      flash.now[:notice] = "Customer table was successfully updated"
      redirect_to customer_tables_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /customer_tables/1 or /customer_tables/1.json
  def destroy
    @customer_table.soft_delete

    respond_to do |format|
      format.html do
        flash[:notice] = "Customer table was successfully deleted"
        redirect_to customer_tables_path
      end
      format.turbo_stream
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer_table
      @customer_table = CustomerTable.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def customer_table_params
      params.require(:customer_table).permit(:customer_table_number)
    end
end

app/helpers/customer_tables_helper.rb
module CustomerTablesHelper
end

app/views/customer_tables/_form.html.erb
<%= form_with(model: customer_table, class: "contents") do |form| %>
  <% if customer_table.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(customer_table.errors.count, "error") %> prohibited this customer_table from being saved:</h2>

      <ul>
        <% customer_table.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mt-2 mb-2 block max-w-sm p-6 bg-white border border-gray-200 rounded-lg drop-shadow-lg shadow-sm
                hover:bg-blue-300 dark:hover:bg-lime-100">
    <div>
      <strong><%= form.label :customer_table_number, "Customer Table Number: ", required: true%></strong>
      <%= form.number_field :customer_table_number, in: 1..50, required: true,
                            class: "mt-2 px-4 py-2 bg-gray-100 border border-gray-300 text-gray-700
                            rounded-lg text-sm shadow-sm focus:outline-none focus:ring-2 focus:ring-sky-500
                            focus:border-sky-500 transition duration-200" %>
    </div>

    <div class="inline">
      <%= form.submit data: { turbo_frame: "_top" }, class: "mt-2 mb-1 rounded-lg py-3 px-3 bg-blue-600 text-white font-small cursor-pointer" %>
      <%= link_to "Cancel", customer_tables_path, data: { turbo_frame: "_top" },
                  class: "ml-2 rounded-lg py-3 px-5 bg-gray-300 inline-block font-medium" %>
    </div>

  </div>
<% end %>

app/views/customer_tables/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(@customer_table)  %>

app/views/customer_tables/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing customer table</h1>

  <%= turbo_frame_tag @customer_table do %>
    <%= render "form", customer_table: @customer_table %>
  <% end %>
</div>

app/views/customer_tables/index.html.erb
<div class="mx-auto w-full">
  <% content_for :title, "Customer Tables" %>

  <div>
    <%= render 'layouts/navigation' %>
  </div>

  <div class="flex justify-center mt-3">
    <%= turbo_frame_tag "customer_table" do %>

      <div class="flex justify-center items-center mt-5">
        <h1 class="font-bold text-3xl">Customer Tables</h1>
      </div>

      <div class="container mt-3 px-5 bg-white border-gray-300 rounded-lg shadow-sm">

        <!--Table Header-->
        <div class="grid grid-cols-2 px-5 text-white bg-pink-500 px-4 py-2 rounded-t-lg">
          <div class="font-bold flex justify-center">Table Number</div>
        </div>

        <!--Table body-->
        <% @customer_tables.each do |table| %>
          <%= turbo_frame_tag table do %>
            <div class="grid grid-cols-2 border-b border-gray-300">
              <div class="border border-gray-300 py-3 flex justify-center"><%=table.customer_table_number %></div>
              <div class="border border-gray-300 py-3 flex justify-center">

                <%= link_to edit_customer_table_path(table) do %>
                  <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                    <path stroke="green" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m14.304 4.844 2.852 2.852M7 7H4a1 1 0 0 0-1 1v10a1 1 0 0 0 1 1h11a1 1 0 0 0 1-1v-4.5m2.409-9.91a2.017 2.017 0 0 1 0 2.853l-6.844 6.844L8 14l.713-3.565 6.844-6.844a2.015 2.015 0 0 1 2.852 0Z"/>
                  </svg>
                <%end %>

                <%= button_to table, method: :delete, data: { turbo_confirm: "Are you sure?" } do %>
                  <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                    <path stroke="red" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 7h14m-9 3v8m4-8v8M10 3h4a1 1 0 0 1 1 1v3H9V4a1 1 0 0 1 1-1ZM6 7h12v13a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V7Z"/>
                  </svg>
                <%end %>

              </div>
            </div>
          <%end %>
        <%end %>
      </div>

      <div class="apple_pagination mt-3">
        <%= will_paginate @customer_tables, :container => false %>
      </div>

      <div class="mt-2 flex inline-block items-center justify-center">
        <%= link_to "Add Customer table", new_customer_table_path,
                    data: { turbo_frame: "new_customer_table" },
                    class: "ml-2 rounded-lg py-3 px-5 bg-green-300 inline-block font-medium"  %>
      </div>
    <%end %>
  </div>
</div>

app/views/customer_tables/new.html.erb
<div>
  <h1 class="font-bold text-4xl px-4 py-2">New customer table</h1>

  <%=turbo_frame_tag "customer_table" do %>
    <%= render "form", customer_table: @customer_table%>
  <%end %>
</div>