config/routes.rb
Rails.application.routes.draw do
  resources :customers do
    resources :order_items, except: [ :index ]
    resources :payment_details, except: [ :update, :edit ]
  end

  devise_for :users

  resources :menu_items

  resources :customer_tables

  resources :users, only: [ :index ]

  root "menu_items#index"
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
  has_many :order_items
  has_many :customers, through: :order_items

  validates :menu_items, presence: true
  validates :menu_item_price, presence: true, numericality: {
    greater_than_or_equal_to: 1 }

  def self.search_by_menu_name(menu_name_query)
    if menu_name_query.present?
      where("menu_items LIKE ? ", "%#{menu_name_query}%")
    else
      all
    end
  end
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController
  before_action :authenticate_user!, except: [ :index ]
  before_action :set_menu_item, only: %i[ show edit update destroy]

  # GET /menu_items or /menu_items.json
  def index
    list_menu_items = ::ListMenuItems.new(params)
    @menu_items = list_menu_items.fetch_menu_items

    respond_to do |format|
      format.html { }

      format.json {
        render json: @menu_items
      }
    end
  end

  def show
    respond_to do |format|
      format.html
      format.json { render json: @menu_item }
    end
  end

  # GET /menu_items/new
  def new
    @menu_item = MenuItem.new
  end


  # POST /menu_items or /menu_items.json
  def create
    @menu_item = MenuItem.new(menu_item_params)
    if @menu_item.save
      respond_to do |format|
        format.html { redirect_to menu_items_path, notice: "Menu item was successfully created." }
        format.json { render json: @menu_item }
      end
    else
      respond_to do |format|
        format.html {   render :new, status: :unprocessable_entity }
        format.json { render json: { error: @menu_item.errors.full_messages }, status: :unprocessable_entity }
      end
    end
  end

  # GET /menu_items/1/edit
  def edit
  end

  # PATCH/PUT /menu_items/1 or /menu_items/1.json
  def update
    if @menu_item.update(menu_item_params)
      respond_to do |format|
        format.html { redirect_to menu_items_path, notice: "Menu Item was successfully updated." }
        format.json { render json: @menu_item }
      end
    else
      respond_to do |format|
        format.html {  render :edit, status: :unprocessable_entity }
        format.json { render json: { error: @menu_item.errors.full_messages }, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menu_items/1 or /menu_items/1.json
  def destroy
    if @menu_item
      @menu_item.destroy!
      respond_to do |format|
        format.html do
          flash.now[:notice] = "Menu item was successfully deleted."
          redirect_to menu_items_path
        end
        format.turbo_stream
        format.json { render json: @menu_item }
      end
    else
      respond_to do |format|
        binding.pry
        format.json { render json: { error: "Menu Item not Found " }, status: :not_found }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menu_item
      @menu_item = MenuItem.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def menu_item_params
      params.require(:menu_item).permit(:menu_items, :menu_item_price)
    end
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/views/menu_items/_form.html.erb
<%= form_with(model: menu_item, class: "contents") do |form| %>
  <% if menu_item.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(menu_item.errors.count, "error") %> prohibited this menu_item from being saved:</h2>

      <ul>
        <% menu_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <strong><%= form.label :menu_items, "Menu Item"%></strong>
    <%= form.text_field :menu_items, placeholder: "Enter menu item name",
                        class: "mt-2 px-3 py-2 block md:w-2/3 bg-gray-100 border border-gray-300 text-gray-700
                                rounded-lg text-md shadow-sm focus:outline-none focus:ring-2 focus:ring-sky-500
                                focus:border-sky-500 transition duration-200" %>

  </div>

  <div>
    <strong><%= form.label :menu_item_price, "Price"%></strong>
    <%= form.number_field :menu_item_price, in: 1.0..1000.0, placeholder: "Enter price",
                          class: "mt-2 block md:w-2/3 px-3 py-2 bg-gray-100 border text-gray-700 border-gray-300
                                 rounded-lg text-md shadow-sm focus:outline-none focus:ring-2 focus:ring-sky-500
                                 focus:border-sky-500 transition duration-200" %>
  </div>

  <div class="inline">
    <%= form.button data: { turbo_frame: "_top" }, class: "mt-3 rounded-lg py-3 px-5 bg-green-300 text-black inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/menu_items/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(@menu_item)%>

app/views/menu_items/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing menu item</h1>

  <%= turbo_frame_tag @menu_item do%>
    <%= render "form", menu_item: @menu_item %>
    <%= link_to "Cancel", menu_items_path, data: { turbo_frame: "_top" },
                class: "ml-2 mb-2 rounded-lg py-3 px-5 bg-red-100 inline-block font-medium" %>
  <%end %>
</div>

app/views/menu_items/index.html.erb
<div class="mx-auto w-full">
  <% content_for :title, "Menu items" %>

  <div>
    <%= render 'layouts/navigation' %>
  </div>

  <div class=" flex justify-center mt-3">
    <%= turbo_frame_tag "menu_items_page" do %>

      <div class="px-4 py-1">
        <%= form_with url: menu_items_path, method: :get do |form| %>
          <div class="mb-1">
            <%= form.label :menu_name_query, "Search Menu Item: ", class: "text-sm italic font-bold px-3"%>
            <%= form.text_field :menu_name_query, value: params[:menu_name_query], placeholder: "Enter Menu Item name",
                                class: " md:w-3/6 bg-gray-100 px-3 py-1 border border-gray-300 text-gray-700
                                  text-md shadow-sm rounded-lg focus:outline-none focus:ring-2 focus:ring-sky-500
                                  focus:border-sky-500 transition duration-200"%>
          </div>

          <div>
            <%= form.submit "Search", class: "rounded-md py-1 px-3 bg-blue-600 text-white font-medium
                                            cursor-pointer hover:bg-blue-900"%>
          </div>
        <% end %>
      </div>

      <div class="flex justify-center items-center mt-1">
        <h1 class="font-bold text-4xl">Menu items</h1>
      </div>

      <div class="container mt-3 px-5 bg-white border-gray-300 rounded-lg shadow-sm">

        <% if @menu_items.present? %>
          <!--Table header-->
          <div class="<%= user_signed_in? ? 'grid grid-cols-3 text-white bg-pink-500 py-2 rounded-t-lg' :
                            'grid grid-cols-2 text-white bg-pink-500 py-2 rounded-t-lg' %>">
            <div class="font-bold flex justify-center">Item</div>
            <div class="font-bold flex justify-center">Price (Nu)</div>
          </div>

          <!--Table Body-->
          <% @menu_items.each do |menu_item| %>
            <%= turbo_frame_tag menu_item do %>
              <div class="<%= user_signed_in? ? 'grid grid-cols-3 border-b border-gray-300' : 'grid grid-cols-2 border-b border-gray-300' %>">
                <div class="border border-gray-300 px-4 py-2 flex justify-center"><%= menu_item.menu_items %></div>
                <div class="border border-gray-300 px-4 py-2 flex justify-center"><%= menu_item.menu_item_price %></div>
                <% if user_signed_in? %>
                  <div class="border border-gray-300 px-4 py-2 flex justify-center">
                    <%= link_to edit_menu_item_path(menu_item) do %>
                      <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                        <path stroke="green" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m14.304 4.844 2.852 2.852M7 7H4a1 1 0 0 0-1 1v10a1 1 0 0 0 1 1h11a1 1 0 0 0 1-1v-4.5m2.409-9.91a2.017 2.017 0 0 1 0 2.853l-6.844 6.844L8 14l.713-3.565 6.844-6.844a2.015 2.015 0 0 1 2.852 0Z"/>
                      </svg>
                    <%end %>

                    <%= button_to menu_item, method: :delete, data: { turbo_confirm: "Are you sure?", turbo_frame: "_top" } do %>
                      <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                        <path stroke="red" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 7h14m-9 3v8m4-8v8M10 3h4a1 1 0 0 1 1 1v3H9V4a1 1 0 0 1 1-1ZM6 7h12v13a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V7Z"/>
                      </svg>
                    <%end %>
                  </div>
                <%end %>
              </div>
            <%end %>
          <%end %>

        <% else %>
          <%if params[:menu_name_query].present?%>
            <p class="flex justify-center text-red-500 font-bold">No Menu Item: <%= params[:menu_name_query] %> found </p>
          <%else %>
            <p class="flex justify-center text-red-500 font-bold">No Menu Item Data found</p>
          <% end %>
        <% end %>
      </div>

      <div id= "pagination" class="apple_pagination mt-3">
        <%= will_paginate @menu_items, :container => false %>
      </div>

      <% if user_signed_in? %>
        <div class="flex justify-center">
          <% if params[:commit].present? %>
            <%= link_to "Back to Menu Items", menu_items_path,
                        class: "mt-2 ml-2 rounded-lg py-3 px-5 bg-gray-300 hover:bg-green-200 inline-block font-medium"%>
          <%end %>

          <%= link_to "Add new Menu Item", new_menu_item_path,
                      data: { turbo_frame: "new_menu_item" },
                      class: "mt-3 ml-2 rounded-lg py-3 px-5 bg-green-300 inline-block font-medium"%>
        </div>
      <%end %>
    <%end %>
  </div>
</div>

app/views/menu_items/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New menu item</h1>

  <%= turbo_frame_tag "menu_items_page" do %>
    <%= render "form", menu_item: @menu_item %>
    <%= link_to "Back to menu items", menu_items_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-300 inline-block font-medium" %>
  <% end %>
</div>