config/routes.rb
Rails.application.routes.draw do
  resources :customers do
    resources :order_items, except: [ :index ]
    resources :payment_details, except: [ :update, :edit ]
  end

  devise_for :users

  resources :menu_items

  resources :customer_tables

  resources :users, only: [ :index ]

  root "menu_items#index"
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :customer_table, optional: true
  has_and_belongs_to_many :customer_tables
  has_many :order_items, dependent: :destroy
  has_many :menu_items, through: :order_items
  has_one :payment_detail, dependent: :destroy

  validates :customer_name, presence: true

  enum :payment_method, {
    cash: 0,
    online_payment: 1
  }

  def self.search_by_name(name_query)
    if name_query.present?
      where("customer_name LIKE ?", "%#{name_query}%")
    else
      all
    end
  end

  def self.search_by_date(date_query)
    if date_query.present?
      where("DATE(customers.created_at) = ?", date_query)
    else
      all
    end
  end
end

app/models/customer_table.rb
class CustomerTable < ApplicationRecord
  has_many :customers
  has_and_belongs_to_many :customers

  validates :customer_table_number, uniqueness: true, presence: true, numericality: {
    greater_than_or_equal_to: 1 }

  def soft_delete
    update(deleted_at: Time.current)
  end

  default_scope { where(deleted_at: nil) }
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_customer, only: %i[ show ]
  before_action :get_source, only: [ :new, :create ]

  SORTABLE_COLUMNS = %w[customer_name payment_amt].freeze

  def index
    date_query = params[:date_query]
    name_query = params[:name_query]

    def sort_column
      params[:sort] if SORTABLE_COLUMNS.include?(params[:sort])
    end

    sort_direction = params[:direction].presence_in(%w[asc desc])

    if name_query.present? && date_query.present?
      @customers = Customer.order(Arel.sql("#{sort_column} #{sort_direction}"))
                          .search_by_name(params[:name_query])
                          .search_by_date(params[:date_query])
                          .paginate(page: params[:page], per_page: 4)
    elsif date_query.present?
      @customers = Customer.order(Arel.sql("#{sort_column} #{sort_direction}"))
                           .search_by_date(params[:date_query])
                           .paginate(page: params[:page], per_page: 4)
    elsif name_query.present?
      @customers = Customer.order(Arel.sql("#{sort_column} #{sort_direction}"))
                           .search_by_name(params[:name_query])
                           .paginate(page: params[:page], per_page: 4)
    else
      if params[:name_query].nil? && params[:date_query].nil?
        @customers = Customer.order(created_at: :desc).paginate(page: params[:page], per_page: 4)

        respond_to do |format|
          format.html
          format.json {
            render json: CustomerSerializer.new(@customers).serializable_hash.to_json
          }
        end
      else
        @customers = Customer.order(Arel.sql("#{sort_column} #{sort_direction}")).paginate(page: params[:page], per_page: 4)
      end
    end
  end
  def show
    @order_items = @customer.order_items.includes(:menu_item)
    @grand_total = @order_items.sum("menu_item_price * quantity")
    @payment = params[:payment]
  end

  # GET /customers/new
  def new
    @customer = Customer.new
    @source = params[:source]
  end

  # POST /customers or /customers.json
  def create
    @customer = Customer.new(customer_params)
    @customer.payment_amt = 0.0

    if params[:customer][:customer_table_ids].present?
      table_ids = params[:customer][:customer_table_ids].reject(&:blank?)
      @customer.customer_tables = CustomerTable.where(id: table_ids)
      @customer.customer_table = nil
    else

      @customer.customer_table = CustomerTable.find(params[:customer][:customer_table_id])
      @customer.customer_tables.clear
    end

    if @customer.save
      flash[:notice] = "Customer was successfully created"
      redirect_to @customer
    else
      render :new, status: :unprocessable_entity
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def customer_params
      params.require(:customer).permit(:customer_name, :customer_table_id, customer_table_ids: [])
    end

    def get_source
      @source = params[:source]
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_with(model: customer, class: "contents") do |form| %>
  <% if customer.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>
      <ul>
        <% customer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :customer_name, "Customer name: ", required: true, class: "font-bold"%>
    <%= form.text_field :customer_name, placeholder: "Enter customer name",required: true,
                        class: "mt-2 md:w-1/3 bg-gray-100 px-3 py-1 border border-gray-300 text-gray-700
                                text-md shadow-sm rounded-lg focus:outline-none focus:ring-2 focus:ring-sky-500
                                focus:border-sky-500 transition duration-200"%>
  </div>

  <div>
    <%= form.label :customer_table_id, "Customer Table Number: ", required: true, class: "font-bold"%>

    <% if @source.present? %>
      <%= form.select :customer_table_ids, CustomerTable.all.collect {|table| [table.customer_table_number, table.id] },
                      {prompt: "Select Multiple Table"},
                      multiple: true,
                      required: true,
                      class: "mt-4 md:w-1/3 bg-gray-100 px-3 py-4 border border-gray-300 text-gray-700
                                text-md shadow-sm rounded-lg focus:outline-none focus:ring-2 focus:ring-sky-500
                                focus:border-sky-500 transition duration-200"%>
      <%# CustomerTable.all.each do |table| %>
<!--        <div class="mt-4 md:w-1/3">-->
          <%#= check_box_tag "customer_table_ids[]", table.id, false, id: "customer_table_#{table.id}" %>
          <%#= label_tag "customer_table_#{table.id}", table.customer_table_number, class: "ml-2 text-gray-700 text-md" %>
<!--        </div>-->
      <%# end %>

      <%else %>
      <%= form.select :customer_table_id, CustomerTable.all.collect {|table| [table.customer_table_number, table.id] },
                      {prompt: "Select Table"},
                      required: true,
                      class: "mt-4 md:w-1/3 bg-gray-100 px-3 py-1 border border-gray-300 text-gray-700 text-md shadow-sm rounded-lg focus:outline-none focus:ring-2 focus:ring-sky-500 focus:border-sky-500 transition duration-200"%>
    <% end %>
  </div>

  <div class="inline">
    <%= form.submit class: "mt-3 rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/customers/index.html.erb
<div class="mx-auto w-full">

  <div class="mx-auto h-lvh">
    <div>
      <%= render 'layouts/navigation' %>
    </div>

    <h1 class="flex justify-center font-bold text-2xl">Customers</h1>

    <div class="mx-auto w-max">
<!--    name and date filter-->
    <div class="px-4 py-1">
      <%= form_with url: customers_path, method: :get do |form| %>
        <div class="mb-1">
          <%= form.label :name_query, "Search Customer by name: ", class: "text-sm italic font-bold px-3"%>
          <%= form.text_field :name_query, value: params[:name_query], placeholder: "Enter the name of the customer",
                              class: "mt-2 md:w-1/3 bg-gray-100 px-3 py-1 border border-gray-300 text-gray-700
                                  text-md shadow-sm rounded-lg focus:outline-none focus:ring-2 focus:ring-sky-500
                                  focus:border-sky-500 transition duration-200"%>
        </div>

        <div class="mb-1">
          <%= form.label :date_query, "Search Customer by Date: ", class: "text-sm italic font-bold px-3"%>
          <%= form.date_field :date_query, value: params[:date_query],
                              class: "mt-2 md:w-1/3 bg-gray-100 px-3 py-1 border border-gray-300 text-gray-700
                                  text-md shadow-sm rounded-lg focus:outline-none focus:ring-2 focus:ring-sky-500
                                  focus:border-sky-500 transition duration-200"%>
        </div>

        <div class="mb-2">
          <%= form.submit "Search", class: "w-1/6 mt-3 rounded-md py-1 px-3 bg-blue-600 text-white font-medium
                                            cursor-pointer hover:bg-blue-900"%>
        </div>
      <% end %>
    </div>

      <% if @customers.present? %>
        <table class="text-center mt-2 table-auto px-5 bg-white border border-gray-300">
          <thead class="bg-pink-500 text-white">
          <tr>
            <%= sortable_table_header "Customer Name", :customer_name , :customers_path, class: "px-3 "%>
            <th class="px-4 py-2">Customer Table Number</th>
            <th> Status</th>
            <%= sortable_table_header "Total Payment", :payment_amt, :customers_path, class: "px-5"%>
            <th class="px-5">Payment (Cash/jrn)</th>
            <th>Action</th>
          </tr>
          </thead>

          <tbody>
          <% @customers.each do |customer| %>
            <% total=customer.order_items.includes(:menu_item).sum("menu_item_price * quantity") %>
            <tr>
              <td class="border border-gray-300 px-4 py-2 "><%= customer.customer_name %></td>

              <!--Customer table-->
              <%if customer.customer_tables.any? %>
                <td class="px-4 py-2 border border-gray-300 ">
                  <%= customer.customer_tables.map(&:customer_table_number).join(',')%>
                </td>
              <% elsif customer.customer_table.present? %>
                <td class="border border-gray-300 px-4 py-2"><%= customer.customer_table.customer_table_number %></td>
              <%else %>
                <td class="border border-gray-300 px-4 py-2">No customer table</td>
              <%end %>

              <!--Payment Status-->
              <td class="border border-gray-300 px-4 py-2 <%= customer.payment_status == 'Payment Done' ? 'text-green-500' : 'text-red-500' %>">
                <%= customer.payment_status || "Payment Pending" %>
              </td>

              <td class="border border-gray-300 px-4 py-2"><strong>Nu.<%= total %></strong></td>

              <!--Payment Method-->
              <% if customer.payment_status == "Payment Done"%>
                <td class="border border-gray-300 px-4 py-2">
                  <%= customer.payment_method == "cash" ? "Cash" : customer.payment_detail.journal_number%>
                </td>
              <%else %>
                <td class="border border-gray-300 px-4 py-2"></td>
              <% end %>

              <td class="border border-gray-300 px-4 py-2"><%= link_to "Show this Customer", customer,
                                                                       class: "mt-1 ml-1 rounded-lg py-3 px-5 bg-gray-200
                                                                       hover:bg-gray-100 inline-block font-medium" %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>

        <div class="apple_pagination">
          <%= will_paginate @customers, :container => false %>
        </div>

      <% else %>
        <%if params[:name_query].present? && params[:date_query].present? %>
          <p class="flex justify-center text-red-500 font-bold">No Customer Name: <%= params[:name_query] %> found on Date: <%= params[:date_query] %></p>
        <%elsif params[:date_query] %>
          <p class="flex justify-center text-red-500 font-bold">No Customer on Date: <%= params[:date_query] %> found</p>
        <%elsif params[:name_query] %>
          <p class="flex justify-center text-red-500 font-bold">No Customer Name: <%= params[:name_query] %> found</p>
        <%else %>
          <p class="flex justify-center text-red-500 font-bold">No Customer Data found</p>
        <% end %>
      <%end %>

      <div class="flex justify-center">
        <% if params[:commit].present? %>
          <%= link_to "Back to Customers", customers_path,
                    class: "mt-2 ml-2 rounded-lg py-3 px-5 bg-gray-300 hover:bg-green-200 inline-block font-medium"%>
        <%end %>

        <!--PopUp for add customer tables-->
        <div data-controller="popup">
          <button data-action="click->popup#openPopup" class="mt-2 ml-2 rounded-lg py-3 px-5 bg-green-300
                                                       hover:bg-green-200 inline-block font-medium">Add customer</button>
          <%= render "shared/popup", controller_name: "popup" do%>
            <h1 class="flex justify-center font-bold ">Do you want to Join customer table ?</h1>
            <div class="flex justify-center">
              <%= link_to "Yes", new_customer_path(source: "Join_Tables"), class: "mt-2 ml-2 rounded-lg py-3 px-5 bg-green-300 hover:bg-green-200 inline-block font-medium" %>
              <%= link_to "No", new_customer_path, class: "mt-2 ml-2 rounded-lg py-3 px-5 bg-red-100 inline-block font-medium" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/customers/new.html.erb
<div class="flex justify-center">
  <div class="mx-auto md:w-2/3 w-full">
    <h1 class="font-bold text-4xl">New customer</h1>

    <div class="mt-3 block p-6 bg-white border border-gray-200 rounded-lg drop-shadow-lg shadow-sm
                hover:bg-blue-300 dark:hover:bg-lime-100">
      <%= render "form", customer: @customer, order_item: @order_item %>
      <%= link_to "Back to customers", customers_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-300 inline-block font-medium" %>
    </div>
  </div>
</div>

app/views/customers/show.html.erb
<% if controller_name == "customers"%>
  <div>
    <%= render 'layouts/navigation' %>
  </div>
<%end %>

<div class="mx-auto md:w-2/3 w-full">
  <h1 class="flex justify-center font-bold text-2xl">Customer Details</h1>

  <div class="flex justify-center">
    <div class="mt-3 block max-w-sm p-6 bg-white border border-gray-200 rounded-lg drop-shadow-lg shadow-sm
                hover:bg-blue-300 dark:hover:bg-lime-100">
      <p class="flex justify-center">
        <strong>Customer Name: </strong>
        <%= @customer.customer_name %>
      </p>

      <% if @customer.customer_tables.any? %>
        <p class="flex justify-center">
          <strong>Customer Table Number: </strong>
          <strong><%= @customer.customer_tables.map(&:customer_table_number).join(',') %></strong>
        </p>
      <%elsif @customer.customer_table.present?%>
        <p class="flex justify-center">
          <strong>Customer Table Number: </strong>
          <%= @customer.customer_table.customer_table_number %>
        </p>
      <%else %>
        <P>No Customer table</P>
      <% end %>
    </div>
  </div>

  <h1 class="mt-3 flex justify-center font-bold text-2xl">Order Items</h1>

  <div class="mx-auto flex justify-center">
    <%= turbo_frame_tag "order_items_page" do %>
      <div class="px-5 bg-white border-gray-300 rounded-lg shadow-sm mx-auto w-full">
        <% if @order_items %>

          <!-- Table Header -->
          <div class="grid grid-cols-5 text-center px-5 text-white bg-pink-500 py-1 rounded-t-md">
            <div class="font-bold px-4 py-2">Menu Item</div>
            <div class="font-bold px-4 py-2">Quantity</div>
            <div class="font-bold px-4 py-2">Price</div>
            <div class="font-bold px-4 py-2">Total (Nu)</div>
            <% unless @customer.payment_status == "Payment Done" %>
              <div class="font-bold px-4 py-2"> Action </div>
            <%end %>
          </div>

          <!-- Table Body -->
          <% @order_items.each do |order_item| %>
            <%=turbo_frame_tag order_item do %>
              <div class="grid grid-cols-5 text-center px-5 py-1 border border-gray-300">
                <div class="px-4 py-1"><%= order_item.menu_item.menu_items if order_item.menu_item %></div>
                <div class="px-4 py-1"><%= order_item.quantity %></div>
                <div class="px-4 py-1"><%= order_item.menu_item.menu_item_price %></div>
                <div class="px-4 py-1"><%= number_with_precision(order_item.menu_item.menu_item_price * order_item.quantity, precision: 2) %></div>
                <% unless @customer.payment_status == "Payment Done" %>
                  <div class="px-4 py-1 flex justify-center items-center">
                    <%= link_to edit_customer_order_item_path(@customer.id, order_item, {source: @source}) do %>
                      <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                        <path stroke="green" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m14.304 4.844 2.852 2.852M7 7H4a1 1 0 0 0-1 1v10a1 1 0 0 0 1 1h11a1 1 0 0 0 1-1v-4.5m2.409-9.91a2.017 2.017 0 0 1 0 2.853l-6.844 6.844L8 14l.713-3.565 6.844-6.844a2.015 2.015 0 0 1 2.852 0Z"/>
                      </svg>
                    <% end %>
                    <%#if controller_name == "customers" %>
                      <%= button_to customer_order_item_path(@customer, order_item, {source: @source}), method: :delete, data: { turbo_confirm: "Are you sure?" } do %>
                        <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                          <path stroke="red" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 7h14m-9 3v8m4-8v8M10 3h4a1 1 0 0 1 1 1v3H9V4a1 1 0 0 1 1-1ZM6 7h12v13a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V7Z"/>
                          </svg>
                     <% end %>
                    <%#end %>
                  </div>
                <% end %>
              </div>
            <%end %>
          <% end %>

          <%#= turbo_frame_tag "grand_total" do %>
            <!--Total Payment-->
            <div class="flex justify-center bg-pink-500 rounded-b-lg border border-gray-300 px-4 py-2">
              <div class="px-4 py-2"><strong>Grand Total</strong></div>
              <div class="font-bold px-4 py-2">Nu. <%=controller_name == "payment_details" ? @total_payment : @grand_total %></div>
            </div>
          <%#end %>

          <div class="mt-2 flex justify-center">
            <% unless @customer.payment_status == "Payment Done" %>
              <%= link_to "Add Order Items", new_customer_order_item_path(@customer),
                          class: "ml-2 rounded-lg py-3 px-5 bg-green-300 inline-block font-medium" %>
            <%end %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="mt-2 mb-2 flex justify-center">
    <% unless controller_name == "payment_details" %>
      <div class="flex items-center">
        <%= link_to "Back to Customers" , customers_path,
                    class: "ml-2 rounded-lg py-3 px-5 bg-gray-300 inline-block font-medium" %>
      </div>
    <%end %>

    <!--    Popup for payment method-->
    <% unless controller_name == 'payment_details' %>
      <% unless @customer.payment_status == "Payment Done"%>
        <% unless @grand_total == 0 %>
          <div data-controller="popup" class="flex justify-center inline-block ml-2">
            <button data-action="click->popup#openPopup" class="mt-2 mb-2 rounded-lg py-3 px-5 bg-red-100 font-medium">
              Checkout this customer
            </button>
            <%= render "shared/popup", controller_name: "popup" do%>
              <h1 class="flex justify-center font-bold ">What is the Customer Payment Method ?</h1>
              <div class="flex justify-center">
                <%= link_to "Online Payment", new_customer_payment_detail_path(@customer, payment: "online_payment"),
                            class: "mt-2 ml-2 rounded-lg py-3 px-5 bg-green-300 hover:bg-green-200 inline-block font-medium" %>
                <%= link_to "Cash", new_customer_payment_detail_path(@customer),
                            class: "mt-2 ml-2 rounded-lg py-3 px-5 bg-gray-300 inline-block font-medium" %>
              </div>
            <%end %>
        <% end %>
        </div>
      <%end %>
    <% end %>
  </div>
</div>

app/views/customers/update.turbo_stream.erb
<turbo-stream action="update" target="grand_total">
  <template>
    <%= turbo_frame_tag "grand_total" do %>
      <div class="flex justify-center bg-pink-500 rounded-b-lg border border-gray-300 px-4 py-2">
        <div class="px-4 py-2"><strong>Grand Total</strong></div>
        <div class="font-bold px-4 py-2">Nu. <%= @total_payment %></div>
      </div>
    <% end %>
  </template>
</turbo-stream>