config/routes.rb
Rails.application.routes.draw do
  resources :customers do
    resources :order_items, except: [ :index ]
    resources :payment_details, except: [ :update, :edit ]
  end

  devise_for :users

  resources :menu_items

  resources :customer_tables

  resources :users, only: [ :index ]

  root "menu_items#index"
end

app/views/layouts/_navigation.html.erb
<nav class="bg-gray-800">
  <div class="mx-auto max-w-7xl px-1 sm:px-6 lg:px-8">
    <div class="relative flex h-16 items-center justify-between">
      <div class="flex space-around">

        <% if user_signed_in? %>
          <%unless controller_name== "menu_items"%>
            <%= link_to "Menu Items", menu_items_path,
                        class: "rounded-md px-3 py-2 text-sm font-medium text-white hover:bg-gray-700 hover:text-white"%>
          <%end %>

          <%unless  controller_name == "customer_tables"%>
            <%= link_to "Customer Tables", customer_tables_path,
                        class: "rounded-md px-3 py-2 text-sm font-medium text-white hover:bg-gray-700 hover:text-white" %>
          <%end %>

          <%unless controller_name=="customers"%>
            <%= link_to "Customers", customers_path,
                        class: "rounded-md px-3 py-2 text-sm font-medium text-white hover:bg-gray-700 hover:text-white"%>
          <%end %>

        <% else %>
          <%= link_to 'Log in', new_user_session_path,
                      class: "rounded-md px-3 py-2 text-sm font-medium text-white hover:bg-gray-700 hover:text-white"%>
          <%= link_to 'Sign up', new_user_registration_path,
                      class: "rounded-md px-3 py-2 text-sm font-medium text-white hover:bg-gray-700 hover:text-white"%>
        <% end %>
      </div>
      <% if user_signed_in?%>
        <%= button_to "Log Out", destroy_user_session_path, method: :delete,
                      class: "rounded-md px-3 py-2 text-sm font-medium text-white hover:bg-gray-700 hover:text-white"%>
      <%end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Restaurant App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
<!--    <meta name="apple-mobile-web-app-capable" content="yes">-->
<!--    <meta name="mobile-web-app-capable" content="yes">-->
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="flex justify-center">
      <% if notice.present?%>
        <p class="py-1 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
      <% end %>

      <% if alert.present? %>
        <p class="py-1 px-3 bg-red-50 mb-5 text-red-500 font-medium rounded-lg inline-block" id="alert"><%= alert %></p>
      <% end %>
    </div>

    <%= yield %>
  </body>
</html>